# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: maplab-common/eigen.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='maplab_common/eigen.proto',
  package='common.proto',
  syntax='proto2',
  serialized_options=None,
  serialized_pb=_b('\n\x19maplab_common/eigen.proto\x12\x0c\x63ommon.proto\"4\n\x08MatrixXf\x12\x0c\n\x04rows\x18\x01 \x01(\r\x12\x0c\n\x04\x63ols\x18\x02 \x01(\r\x12\x0c\n\x04\x64\x61ta\x18\x03 \x03(\x02\"4\n\x08MatrixXd\x12\x0c\n\x04rows\x18\x01 \x01(\r\x12\x0c\n\x04\x63ols\x18\x02 \x01(\r\x12\x0c\n\x04\x64\x61ta\x18\x03 \x03(\x01\"!\n\x11SemiStaticMatrixd\x12\x0c\n\x04\x64\x61ta\x18\x01 \x03(\x01\"!\n\x11SemiStaticMatrixf\x12\x0c\n\x04\x64\x61ta\x18\x01 \x03(\x02')
)




_MATRIXXF = _descriptor.Descriptor(
  name='MatrixXf',
  full_name='common.proto.MatrixXf',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='rows', full_name='common.proto.MatrixXf.rows', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='cols', full_name='common.proto.MatrixXf.cols', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='data', full_name='common.proto.MatrixXf.data', index=2,
      number=3, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=43,
  serialized_end=95,
)


_MATRIXXD = _descriptor.Descriptor(
  name='MatrixXd',
  full_name='common.proto.MatrixXd',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='rows', full_name='common.proto.MatrixXd.rows', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='cols', full_name='common.proto.MatrixXd.cols', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='data', full_name='common.proto.MatrixXd.data', index=2,
      number=3, type=1, cpp_type=5, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=97,
  serialized_end=149,
)


_SEMISTATICMATRIXD = _descriptor.Descriptor(
  name='SemiStaticMatrixd',
  full_name='common.proto.SemiStaticMatrixd',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='data', full_name='common.proto.SemiStaticMatrixd.data', index=0,
      number=1, type=1, cpp_type=5, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=151,
  serialized_end=184,
)


_SEMISTATICMATRIXF = _descriptor.Descriptor(
  name='SemiStaticMatrixf',
  full_name='common.proto.SemiStaticMatrixf',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='data', full_name='common.proto.SemiStaticMatrixf.data', index=0,
      number=1, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=186,
  serialized_end=219,
)

DESCRIPTOR.message_types_by_name['MatrixXf'] = _MATRIXXF
DESCRIPTOR.message_types_by_name['MatrixXd'] = _MATRIXXD
DESCRIPTOR.message_types_by_name['SemiStaticMatrixd'] = _SEMISTATICMATRIXD
DESCRIPTOR.message_types_by_name['SemiStaticMatrixf'] = _SEMISTATICMATRIXF
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

MatrixXf = _reflection.GeneratedProtocolMessageType('MatrixXf', (_message.Message,), dict(
  DESCRIPTOR = _MATRIXXF,
  __module__ = 'maplab_common.eigen_pb2'
  # @@protoc_insertion_point(class_scope:common.proto.MatrixXf)
  ))
_sym_db.RegisterMessage(MatrixXf)

MatrixXd = _reflection.GeneratedProtocolMessageType('MatrixXd', (_message.Message,), dict(
  DESCRIPTOR = _MATRIXXD,
  __module__ = 'maplab_common.eigen_pb2'
  # @@protoc_insertion_point(class_scope:common.proto.MatrixXd)
  ))
_sym_db.RegisterMessage(MatrixXd)

SemiStaticMatrixd = _reflection.GeneratedProtocolMessageType('SemiStaticMatrixd', (_message.Message,), dict(
  DESCRIPTOR = _SEMISTATICMATRIXD,
  __module__ = 'maplab_common.eigen_pb2'
  # @@protoc_insertion_point(class_scope:common.proto.SemiStaticMatrixd)
  ))
_sym_db.RegisterMessage(SemiStaticMatrixd)

SemiStaticMatrixf = _reflection.GeneratedProtocolMessageType('SemiStaticMatrixf', (_message.Message,), dict(
  DESCRIPTOR = _SEMISTATICMATRIXF,
  __module__ = 'maplab_common.eigen_pb2'
  # @@protoc_insertion_point(class_scope:common.proto.SemiStaticMatrixf)
  ))
_sym_db.RegisterMessage(SemiStaticMatrixf)


# @@protoc_insertion_point(module_scope)
