# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: summary_map.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from maplab.protobuf.maplab_common import eigen_pb2 as maplab__common_dot_eigen__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='summary_map.proto',
  package='summary_map.proto',
  syntax='proto2',
  serialized_options=None,
  serialized_pb=_b('\n\x11summary_map.proto\x12\x11summary_map.proto\x1a\x19maplab_common/eigen.proto\"\xaf\x01\n\"UncompressedLocalizationSummaryMap\x12+\n\x0b\x64\x65scriptors\x18\x01 \x01(\x0b\x32\x16.common.proto.MatrixXf\x12\x1b\n\x13G_observer_position\x18\x02 \x03(\x02\x12\x18\n\x10observer_indices\x18\x03 \x03(\r\x12%\n\x1dobservation_to_landmark_index\x18\x04 \x03(\r\"\x86\x01\n\x16LocalizationSummaryMap\x12\x1b\n\x13G_landmark_position\x18\x01 \x03(\x02\x12O\n\x10uncompressed_map\x18\x02 \x01(\x0b\x32\x35.summary_map.proto.UncompressedLocalizationSummaryMap')
  ,
  dependencies=[maplab__common_dot_eigen__pb2.DESCRIPTOR,])




_UNCOMPRESSEDLOCALIZATIONSUMMARYMAP = _descriptor.Descriptor(
  name='UncompressedLocalizationSummaryMap',
  full_name='summary_map.proto.UncompressedLocalizationSummaryMap',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='descriptors', full_name='summary_map.proto.UncompressedLocalizationSummaryMap.descriptors', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='G_observer_position', full_name='summary_map.proto.UncompressedLocalizationSummaryMap.G_observer_position', index=1,
      number=2, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='observer_indices', full_name='summary_map.proto.UncompressedLocalizationSummaryMap.observer_indices', index=2,
      number=3, type=13, cpp_type=3, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='observation_to_landmark_index', full_name='summary_map.proto.UncompressedLocalizationSummaryMap.observation_to_landmark_index', index=3,
      number=4, type=13, cpp_type=3, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=68,
  serialized_end=243,
)


_LOCALIZATIONSUMMARYMAP = _descriptor.Descriptor(
  name='LocalizationSummaryMap',
  full_name='summary_map.proto.LocalizationSummaryMap',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='G_landmark_position', full_name='summary_map.proto.LocalizationSummaryMap.G_landmark_position', index=0,
      number=1, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='uncompressed_map', full_name='summary_map.proto.LocalizationSummaryMap.uncompressed_map', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=246,
  serialized_end=380,
)

_UNCOMPRESSEDLOCALIZATIONSUMMARYMAP.fields_by_name['descriptors'].message_type = maplab__common_dot_eigen__pb2._MATRIXXF
_LOCALIZATIONSUMMARYMAP.fields_by_name['uncompressed_map'].message_type = _UNCOMPRESSEDLOCALIZATIONSUMMARYMAP
DESCRIPTOR.message_types_by_name['UncompressedLocalizationSummaryMap'] = _UNCOMPRESSEDLOCALIZATIONSUMMARYMAP
DESCRIPTOR.message_types_by_name['LocalizationSummaryMap'] = _LOCALIZATIONSUMMARYMAP
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

UncompressedLocalizationSummaryMap = _reflection.GeneratedProtocolMessageType('UncompressedLocalizationSummaryMap', (_message.Message,), dict(
  DESCRIPTOR = _UNCOMPRESSEDLOCALIZATIONSUMMARYMAP,
  __module__ = 'summary_map_pb2'
  # @@protoc_insertion_point(class_scope:summary_map.proto.UncompressedLocalizationSummaryMap)
  ))
_sym_db.RegisterMessage(UncompressedLocalizationSummaryMap)

LocalizationSummaryMap = _reflection.GeneratedProtocolMessageType('LocalizationSummaryMap', (_message.Message,), dict(
  DESCRIPTOR = _LOCALIZATIONSUMMARYMAP,
  __module__ = 'summary_map_pb2'
  # @@protoc_insertion_point(class_scope:summary_map.proto.LocalizationSummaryMap)
  ))
_sym_db.RegisterMessage(LocalizationSummaryMap)


# @@protoc_insertion_point(module_scope)
